### ISSUE TITLE
Repeat the results on public datasets like MVTec, VisA etc.

### ISSUE THREAD

**Issue by TengliEd** [caoyunkang/GroundedSAM-zero-shot-anomaly-detection#10]
Hi, @caoyunkang 
I am very interested in repeating SOTA in benchmark datasets. Can you release the code on prompt engineering and post-processing described in your paper?

Cheers
Teng

**Comment by caoyunkang** [comment]
> Hi, @caoyunkang 
> I am very interested in repeating SOTA in benchmark datasets. Can you release the code on prompt engineering and post-processing described in your paper?
> 
> Cheers
> Teng

Hi, thanks for your interest. This repo only contains SAA at this moment. We are cleaning our code for SAA+ and will release it in the near future😁

Yunkang

**Comment by tzjtatata** [comment]
I found that the results can not be re-produced without prompts and "background" text. In most test image on VisA or mvtec-AD, the simple prompt like 'defect' or 'anomaly' and even more accurate prompt like 'overlong wick' or 'wick'(as in the paper, figure 1) are useless for SAM to detect or segment the defects. 
In fact, the results of current code is poor than original SAM with controllable bounding boxes and points.

**Comment by caoyunkang** [comment]
> I found that the results can not be re-produced without prompts and "background" text. In most test image on VisA or mvtec-AD, the simple prompt like 'defect' or 'anomaly' and even more accurate prompt like 'overlong wick' or 'wick'(as in the paper, figure 1) are useless for SAM to detect or segment the defects. 
> In fact, the results of current code is poor than original SAM with controllable bounding boxes and points. 

actually, SAM with manual controllable prompts would produce reasonable results but require large human efforts. In contrast, SAA/SAA+ could generate segmentation results automatically. We will release the revamped SAA+ for evaluation soon. Best.

**Comment by caoyunkang** [comment]
Hi, @TengliEd . Please refer to the new branch SAA-plus for the updated version. Best. :)

**Comment by tzjtatata** [comment]
It is still hard to repeat the performance in the paper.
![1686126134150](https://github.com/caoyunkang/Segment-Any-Anomaly/assets/9402821/8f8b5fcc-9a8f-4bd1-9428-950dd872406b)
I try some samples in MVTec with their anomaly type as the description and their dataset name as object name. Further, I provide object numbers and mask number with human efforts but still fails to recognize the anomaly.

**Comment by caoyunkang** [comment]
Hello, @tzjtatata 

I recommend consulting the Colab notebook available at this link: [Colab Link](https://colab.research.google.com/drive/12Sh0j92YYmTa0oIuSEWWpPBCpIwCSVhz) to replicate the results outlined in the report. It's important to note that the HuggingFace demo might yield variations in results due to factors such as differences in input image resolution and other finer details.

Should you require any further assistance or clarification, please don't hesitate to reach out.
