### ISSUE TITLE
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '../datasets/VisA_pytorch/1cls\\pipe_fryum\\train'

### ISSUE THREAD

**Issue by ziyouzheilu** [caoyunkang/GroundedSAM-zero-shot-anomaly-detection#16]
The problem is that there is data floder in the pipe_fryum but not train.

**Comment by caoyunkang** [comment]
Sorry, but could you please detail your problem? It seems to be an error about paths. Have you followed the instructions on https://github.com/search?q=spot+the+difference&type=repositories to prepare the dataset?

**Comment by ziyouzheilu** [comment]
Yes,I have done it and this problem is solved.Thanks
