### ISSUE TITLE
Failed to load custom C++ ops. Running on CPU mode Only!

### ISSUE THREAD

**Issue by molu-ggg** [caoyunkang/GroundedSAM-zero-shot-anomaly-detection#17]
曹博你好，按照您的的安装环境安装到linux后出现了Failed to load custom C++ ops. Running on CPU mode Only!  这个问题，以及requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) 我看网上没有有关的解决方案，请问您是否也遇到了这个问题呢？如果没有遇到，您能说一下您的硬件环境吗？

**Comment by caoyunkang** [comment]
很抱歉，暂时无法帮助定位问题。目前版本代码在CUDA11.7，GPU 3090Ti上测试通过。希望您可以尽快解决:)

**Comment by yangchengxin** [comment]
> 
佬，请问您这个问题解决了吗  我换了环境还是有这个报错
