### ISSUE TITLE
huggingface_hub.utils._errors.LocalEntryNotFoundError

### ISSUE THREAD

**Issue by ziyouzheilu** [caoyunkang/GroundedSAM-zero-shot-anomaly-detection#18]
When I python run_VisA_public.py,it appears that huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

**Comment by caoyunkang** [comment]
Hi! It appears to be the problem with HuggingFace connection. I have tried to run run_VisA_public.py on my local server but found no problem. Could you please provide more details, or have you tried my Colab demo (https://colab.research.google.com/drive/12Sh0j92YYmTa0oIuSEWWpPBCpIwCSVhz?usp=sharing)?
