### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\tmpwhdfb3ew\\tmpcnopyh0n.py'

### ISSUE THREAD

**Issue by yangchengxin** [caoyunkang/GroundedSAM-zero-shot-anomaly-detection#19]
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\tmpwhdfb3ew\\tmpcnopyh0n.py'
曹博，请问您遇到过这个bug嘛，该怎么解决呢，期待您的答复~

**Comment by caoyunkang** [comment]
您好！这看起来是环境配置相关的问题，我本地运行时没有遇到相关问题。建议先使用Colab https://colab.research.google.com/drive/12Sh0j92YYmTa0oIuSEWWpPBCpIwCSVhz 进行测试。

**Comment by yangchengxin** [comment]
> 您好！这看起来是环境配置相关的问题，我本地运行时没有遇到相关问题。建议先使用Colab https://colab.research.google.com/drive/12Sh0j92YYmTa0oIuSEWWpPBCpIwCSVhz 进行测试。

好的 谢谢曹博回复，我这边问题解决了

**Comment by jellchou** [comment]
Encountered the same issue，how did u solve it？

**Comment by jellchou** [comment]
> Encountered the same issue，how did u solve it？

Solved it.  Added temp_config_file.close().   In slconfig.py, after the  temp_config_name line.

**Comment by coke531** [comment]
请问你们在本地都是怎么解决的
