### ISSUE TITLE
Inquiries about hugging face reporting errors while using the demo process

### ISSUE THREAD

**Issue by SSSSamZhu** [caoyunkang/GroundedSAM-zero-shot-anomaly-detection#20]
![image](https://github.com/caoyunkang/Segment-Any-Anomaly/assets/100264795/da552c6b-0307-42c0-a20b-26450e0d6544)
It's an exciting job. As shown, I wanted to run the author's demo on hugging face, but unfortunately I failed, expecting it to be resolved.

**Comment by caoyunkang** [comment]
Thank you for your interest in SAA+.

Due to certain implementation nuances, it is important to avoid using spaces in the object names. Instead, kindly consider using underscores `_` to represent spaces in object names. Your cooperation is greatly appreciated.
