### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by sulaiman1988** [caoyunkang/GroundedSAM-zero-shot-anomaly-detection#23]
How to implement a repo on custom datasets to get segmentation for the image by image?
How to Finetune using a custom dataset?

**Comment by PauloFavero** [comment]
I also have the same questions

**Comment by caoyunkang** [comment]
Hello, thank you for your interest in SAA+.

To integrate this repository with your specific dataset on an individual image basis, I recommend consulting the `./demo.py` file. This script provides guidance on processing individual images. It's important to configure the `textual_prompts` and `property_text_prompts` based on the characteristics of your dataset. This enables SAA+ to accurately identify anomalies within your images. If your intention is to apply this to a custom dataset, you can start by examining the `datasets` directory. Begin by creating a `custom.py` file. Subsequently, refer to `SAA/prompts` to document your tailored prompts.

With regards to fine-tuning, I'd like to clarify that our SAA+ is designed to operate without requiring any additional training to accommodate new data. As of now, fine-tuning is not supported by our system. If you have any further inquiries, please don't hesitate to ask.
