### ISSUE TITLE
where is '_C'?

### ISSUE THREAD

**Issue by JiafengtTang** [caoyunkang/GroundedSAM-zero-shot-anomaly-detection#24]

**Comment by djene-mengistu** [comment]
@JiafengtTang  and @caoyunkang , I am still facing this issue, I am wondering if someone have solved this issue.

../GroundingDINO\groundingdino\models\GroundingDINO\ms_deform_attn.py", line 53, in forward
    output = _C.ms_deform_attn_forward(...)
"NameError: name '_C' is not defined "
