### ISSUE TITLE
What is the difference between the results of '*_SAA_plus.jpg' and '*_Saliency.jpg'?

### ISSUE THREAD

**Issue by William9Baker** [caoyunkang/GroundedSAM-zero-shot-anomaly-detection#26]
After the validation mode of SAA+, it can save the results images of  '*_SAA_plus.jpg' and '*_Saliency.jpg', but what is the difference between them? I feel so confused. Thanks.

**Comment by William9Baker** [comment]
Are images of '*_SAA_plus.jpg' and images of '*_Saliency.jpg' both in the form of heat maps? So why are the red areas in the saved heat map inconsistent?

**Comment by caoyunkang** [comment]
Hello! We appreciate your enthusiasm. When we mention "_SAA_plus," we're referring to the predicted anomaly score maps, and "_Saliency" refers to the saliency map generated specifically for the "P_S" (Saliency prompt). Regards.

**Comment by William9Baker** [comment]
> Hello! We appreciate your enthusiasm. When we mention "_SAA_plus," we're referring to the predicted anomaly score maps, and "_Saliency" refers to the saliency map generated specifically for the "P_S" (Saliency prompt). Regards.

Thanks. But I still don’t understand the meaning of the saliency map.

**Comment by William9Baker** [comment]
> > Hello! We appreciate your enthusiasm. When we mention "_SAA_plus," we're referring to the predicted anomaly score maps, and "_Saliency" refers to the saliency map generated specifically for the "P_S" (Saliency prompt). Regards.
> 
> Thanks. But I still don’t understand the meaning of the saliency map.
And why are the red areas inconsistent with '_SAA_plus.jpg' and '_Saliency.jpg'?
