### ISSUE TITLE
Reproduce results on MVTec-AD

### ISSUE THREAD

**Issue by jameslahm** [caoyunkang/GroundedSAM-zero-shot-anomaly-detection#30]
Thank you for your great work! I try to reproduce the results on MVTec-AD following the instructions in README, but the pixel F1 score on MVTec-AD is 37.65 rather than 39.40 which is reported in the paper. Do I need to tune some hyper-parameters to obtain the same result? Thank you!

**Comment by caoyunkang** [comment]
Hello! I apologize for the inconsistencies, which stem from variations in the code versions. To enhance performance, consider adjusting prompts for specific classes. I am confident that there is substantial room for further improvement in MVTec through prompt tuning.

**Comment by jameslahm** [comment]
Thank you!
