### ISSUE TITLE
HF not available 

### ISSUE THREAD

**Issue by cile98** [caoyunkang/GroundedSAM-zero-shot-anomaly-detection#41]
When trying to access HF space, get this error: 
![image](https://github.com/user-attachments/assets/d6ac0bcd-0451-47e1-bc4a-678c1ec7d0df)
Are there any plans on making it available again?

**Comment by caoyunkang** [comment]
@cile98 Thanks for your notifications! I have fixed the HF space. Enjoy it!

**Comment by cile98** [comment]
@caoyunkang Thanks
